# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    service_rpsls:
        class: AppBundle\Service\Rpsls
        arguments: ['%ruleset%']

    service_statistics:
        class: AppBundle\Service\Statistics
        arguments: ['@doctrine.orm.default_entity_manager']
